---
- hosts: webserver
  become: yes
  tasks: 
    - name: install httpd
      yum: name=httpd state=installed 
      when: ansible_os_family=="Debian" 

    - name: Apache httpd config  push
      copy: 
        src : rohit.txt
        dest: /var/rohit.txt
      notify:
        - Apache service restart

    - name: Create directory
      file: path=/var/ninad state=directory
      notify:
        - Apache service restart  

        

  handlers: 
    - name: Apache service restart
      service: 
         name: httpd
         state: restarted  
    
