---
- hosts: dbserver
  become: yes
  gather_facts: false
  vars: 
    global_user: spleder
    global_dbuser: pulser
    global_dbpass: wagnar

  tasks:
    - name: Ensure mysql is installed
      yum :
       name: mysql-server
       state: present
   
    - name: Ensure mysql service is running
      service: 
       name: mysqld 
       state: started

    - name: Ensure mysql-python is installed
      yum: 
       name: MySQL-python 
       state: present

    - name: Create MySQL database
      mysql_db:
       name={{global_user}} state=present

    - name: Create user mint
      mysql_user: name={{global_dbuser}} password={{global_dbpass}} priv='*.*:ALL' state=present
     
   




