---
# tasks file for roles_apache_ex
- name: install httpd
  yum: name=httpd state=installed
  when: ansible_os_family=="Debian"

- name: Apache httpd config  push
  template:
    src : rohit.j2
    dest: /var/rohit.txt
  notify:
   - Apache service restart

- name: Create directory
  file: path=/var/ninad state=directory
  notify:
     - Apache service restart

